#!/bin/bash

docker build -t mongo -f $(dirname $0)/docker_images/Dockerfile_db .
docker run -d --rm --name mongo -p 27017:27017 mongo

docker build -t kugo -f $(dirname $0)/docker_images/Dockerfile $(dirname $0)/docker_images/
docker run -d --rm --name kugo_app --link mongo:db -p 3000:3000 kugo
