# Generated by Django 4.2.1 on 2023-07-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(default="", max_length=25)),
                ("status", models.CharField(default="", max_length=25)),
                ("name", models.CharField(default="", max_length=25, unique=True)),
                ("desc", models.CharField(default="", max_length=255)),
                ("short_id", models.CharField(default="", max_length=255)),
                ("attrs", models.CharField(default="", max_length=255)),
                ("favourite", models.BooleanField(default=False)),
            ],
        ),
    ]
