# Generated by Django 4.2.1 on 2023-07-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
